apiVersion: 1

datasources:
  - name: Turo-Integrator
    type: marcusolsson-json-datasource
    access: proxy
    url: http://localhost:3001/api
    isDefault: true
    jsonData:
      queryParams: ''
    editable: true
